elasticsearch:
    build: ./elasticsearch
    ports:
        - "9200:9200"
    volumes:
        - "./elasticsearch/config:/usr/share/elasticsearch/config"
        - "./elasticsearch/data:/usr/share/elasticsearch/data"
        - "./elasticsearch/logs:/usr/share/elasticsearch/logs"

postgres:
    build: ./postgres
    volumes_from:
        - postgresdata
    environment:
        - POSTGRES_PASSWORD=toto
    ports:
        - "5432:5432"

postgresdata:
    image: busybox
    command: echo "Data volume launched" && true
    volumes:
        - "/User/quentin/Workspace/language/postgres/data:/var/lib/postgresql/data"

pythonapp:
    build: ./application
    command: sh run.sh &
    volumes:
        - "./application/language:/application"
    ports:
        - "8000:8000"
    links:
        - elasticsearch
        - postgres

client:
    build: ./client
    volumes:
        - "./client:/client"
        - "./client/config/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
        - "8080:80"
    links:
        - pythonapp

