elasticsearch:
    build: ./elasticsearch
    ports:
        - "9200:9200"
    volumes:
        - "./elasticsearch/config:/usr/share/elasticsearch/config"

python_app:
    build: ./application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - "../language:/application"
    ports:
        - "8000:8000"

